# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
   # branches: [ master ]
  pull_request:
    branches: [ main ]
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt 
        continue-on-error: false
     
      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false
      - name: Terraform Tflint
        id: tflint-install
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        continue-on-error: false
      - name: Run Terraform Tflint 
        id: Tflint-run
        run: tflint --init  && tflint --module
        continue-on-error: false
     # - name: Execute Terraform Tflint 
     #   id: Tflint-execute
       # run: tflint   --module 
      #  continue-on-error: false

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif   
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif  
      - name: OPA Install
        id: install 
        run: curl -L -o opa https://openpolicyagent.org/downloads/v0.31.0/opa_linux_amd64_static && chmod 755 opa && sudo mv opa /usr/bin
        continue-on-error: false
      - name: Terraform Plan
        id: plan
        run: terraform plan -out plan1 && terraform show -json  plan1 | sed "1d"  > plan1.json
        continue-on-error: false
      - name: Read File
        id: read
        run: cat plan1.json 
        continue-on-error: false
      - name: OPA Test
        id: Test
        run: opa eval --format pretty --data OPA/validate.rego --input plan1.json "data.terraform" 
        #opa eval --fail-defined --format pretty --data OPA/validate.rego --input plan1.json "data.terraform" 
        continue-on-error: false
      - name: Terraform apply
        id: Apply
        run: terraform apply -auto-approve
        continue-on-error: false